# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 25) do

  create_table "articles", :force => true do |t|
    t.column "project_id",       :integer
    t.column "title",            :string
    t.column "content",          :text
    t.column "submitted_by",     :integer
    t.column "is_on_front_page", :boolean,  :default => false
    t.column "is_active",        :boolean,  :default => true
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "assignments", :force => true do |t|
    t.column "project_id", :integer
    t.column "user_id",    :integer
    t.column "role",       :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "bug_versions", :force => true do |t|
    t.column "project_id", :integer
    t.column "name",       :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "comments", :force => true do |t|
    t.column "title",            :string,   :limit => 50, :default => ""
    t.column "comment",          :text
    t.column "created_at",       :datetime,                               :null => false
    t.column "commentable_id",   :integer,                :default => 0,  :null => false
    t.column "commentable_type", :string,   :limit => 15, :default => "", :null => false
    t.column "user_id",          :integer,                :default => 0,  :null => false
  end

  add_index "comments", ["user_id"], :name => "fk_comments_user"

  create_table "enumrecords", :force => true do |t|
    t.column "name",     :string
    t.column "type",     :string
    t.column "position", :integer, :default => 1
  end

  create_table "licenses", :force => true do |t|
    t.column "name", :string
  end

  create_table "packages", :force => true do |t|
    t.column "project_id", :integer
    t.column "name",       :string
    t.column "is_public",  :boolean,  :default => true
    t.column "is_active",  :boolean,  :default => true
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "projects", :force => true do |t|
    t.column "name",                 :string
    t.column "unix_name",            :string
    t.column "description",          :text
    t.column "registration_reason",  :text
    t.column "project_type",         :string
    t.column "project_category",     :string
    t.column "created_at",           :datetime
    t.column "updated_at",           :datetime
    t.column "is_active",            :boolean,  :default => false
    t.column "state",                :string,   :default => "pending"
    t.column "approved_on",          :datetime
    t.column "approved_by",          :integer
    t.column "reject_reason",        :text
    t.column "license_id",           :integer
    t.column "changelog",            :text
    t.column "roadmap",              :text
    t.column "downloads",            :integer
    t.column "next_planned_release", :datetime
  end

  create_table "released_files", :force => true do |t|
    t.column "release_id", :integer
    t.column "filename",   :string
    t.column "filesize",   :integer
    t.column "deleted_at", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "downloads",  :integer
  end

  create_table "releases", :force => true do |t|
    t.column "package_id",    :integer
    t.column "name",          :string
    t.column "release_notes", :text
    t.column "changelog",     :text
    t.column "released_by",   :integer
    t.column "is_active",     :boolean,  :default => true
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
    t.column "created_at",    :datetime
  end

  add_index "taggings", ["tag_id"], :name => "index_taggings_on_tag_id"
  add_index "taggings", ["taggable_id", "taggable_type"], :name => "index_taggings_on_taggable_id_and_taggable_type"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "tasks", :force => true do |t|
  end

  create_table "tracker_items", :force => true do |t|
    t.column "project_id",     :integer
    t.column "assigned_to_id", :integer
    t.column "version_id",     :integer
    t.column "created_by_id",  :integer
    t.column "severity_id",    :integer
    t.column "state",          :string
    t.column "summary",        :string
    t.column "description",    :text
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "resolution_id",  :integer
    t.column "type",           :string,   :limit => 50
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "superuser",                 :boolean,                :default => false
    t.column "full_name",                 :string
  end

end
